{% set name = "sopsy" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sopsy-{{ version }}.tar.gz
  sha256: 7d5a57ebd1a6ca9746e71854e02a1f88bf4129b7aba029e8d282b0247bc83d47

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - pyyaml >=6.0.1
    - go-sops

test:
  imports:
    - sopsy
  commands:
    - pip check
  requires:
    - pip

about:
  summary: SOPS Python wrapper library
  license: GPL-3.0-or-later
  license_file: LICENSE
  home: https://github.com/nikaro/sopsy
  dev_url: https://github.com/nikaro/sopsy
  doc_url: https://sopsy.nikaro.net/

extra:
  recipe-maintainers:
    - FelixMoellerQC
    - pavelzw
